- LICENSE.txt
It is good practice to add a copy of the license to the repository.
> Add a copy of Apache 2.0 license

- shared.css
100vw does not account for eventual horizontal scrollbars, but renders to the full width, which results in an unnecessary vertical scrollbar.
This change should most likely also be made in the master branch at ```/pages/settings/settings.css``` but as this page also has overflow:hidden, I thought I'd leave it like that for now.
> fixed width problem for .hero

- Gruntfile.js
- css/navbarTabs.css
- css/searchbar.css
- css/taskOverlay.css
- index.html
- js/api-wrapper.js
- js/keybindings.js
- js/navbar/navbarTabs.js
- js/sessionRestore.js
- js/tabState.js
- js/taskOverlay.js
- js/webviews.js
- main/main.js
Fixes #5.
This adds the ability to have multiple groups of tabs, called "tasks", open at the same time, and to switch between them (similar to the tab groups feature in Firefox).
Screenshots:
From the tab overlay, dragging and dropping tabs between tasks and renaming tasks is also supported.
> Add a tasks overlay

- main.build.js
- main/main.js
When all tabs are closed in OS X and min is not quitted (by hitting the X button). If you click on the application dock icon, nothing happens.
With this fix, min opens a new tab if you click on the application dock icon in OS X, by listening to the electron `activate` event.
> Fix OS X bug when all tabs are closed

- js/webview/swipeEvents.js
On pinch, the browser-engine sends a ctrl keypress & a mousewheel event. However, platforms other than Mac use ctrl+mouswheel to zoom. Pinch-zooming should be smoother than normal zooming, so the threshold is lowered to 10. Non-mac devices are not affected and cmd+mousewheel is still working.
> Added pinch-zoom support for Mac

- main.build.js
- main/main.js
This makes the shortcut consistent with other browsers.
> Fix inspector shortcut

- .gitignore
- js/bookmarksHistory/bookmarksHistory.js
- js/bookmarksHistory/fullTextSearch.js
- js/bookmarksHistory/placesSearch.js
- js/bookmarksHistory/placesWorker.js
Linter errors have been fixed in `js/bookmarksHistory` 🎉.
The only complaining file is the `placesWorker.js` with some `(no-unused-vars)`. Those warnings will be fixed once we implement the modular approach.
> make Standard 😃, bookmarksHistory

- Gruntfile.js
- js/api-wrapper.js
- js/keybindings.js
- js/tabRestore.js
- js/tabState.js
- js/util/defaultKeyMap.js
- main/main.js
Not sure how you would want this implemented, but here's a start at least.
The tab history is not persistent. Each session can store up to 20 closed tabs on a stack, older tabs are pushed out. No real reason for 20 other than it seemed reasonable. This replaces the shift+mod+t map for opening private tabs that was defined from the menu, now it's just on the custom keybinding. It's shift+mod+t because this is how most major browsers map it, afaik.
Fixes issue #290
> Add ability to restore closed tabs from the current session

- Gruntfile.js
Linux builds fails due to a typographical error in the `electron-installer-debian` `grunt` task. The task looks for `Min-linux-*` whereas `electron:linuxBuild` writes `__dirname` as `min-linux-*`. This change-set fixes that issue.
> Linux builds fails due to typo in application source directory

- js/default.js
Issue #414 was that if the mouse is moving at all, it is not possible to click on tabs. So sometimes when trying to click on a tab, if the mouse moves a few pixels between mouse press and release, the click is cancelled. I have added code that records the mouse position upon pressing the mouse on a tab, and again upon releasing it. The click is only cancelled if the distance between the location of the mouse press and the mouse release is above a small threshold. 
Hope this is to everyone's liking!
> Fixed Issue #414: Added mouse movement threshold for clicking on tabs

- main/main.js
Fixing #411 
This commit adds a protocol handler for "mailto" links. It only delegates the url to the default system mail application.
As a disclaimer, I'm quite new to electron projects (and open source in general), so any input is appreciated.
I thought of creating a separate protocol handling file (so we could handle not only mailto, but magnet links, stream, etc), but wasn't too sure about changing a lot of things, so I just changed enought to fix the issue.
> Fixes issue #411 - Adds mailto protocol handling

- js/navbar/navbarTabs.js
The `auxclick` event is now used instead for non-primary clicks
> fixed: middleclicking on tabs to close does not work in modern electron

- localization/languages/fr-FR.json
Hello,
I have a little doubt about this one. 
The user should write something like my example?
```
^n: open, ^q: close
```
Also, I saw that it's written `"Swipe navigation" // same in french`, however I would (rather) say `Navigation par swipe`. We don't really have word/verb for swipe, I think that the cause of the issue.
> Translate settingsKeyboardShortcutsHelp (fr-FR)

- Gruntfile.js
This removes the need for running "grunt" before "grunt watch:scripts"
the first time.
> Make sure the files build on watch start too

- Gruntfile.js
- README.md
- index.html
- js/webviews.js
- localization/localizationHelpers.js
- package-lock.json
- package.json
- scripts/buildBrowser.js
- scripts/buildLocalization.js
- scripts/buildMain.js
- scripts/buildPreload.js
- scripts/watch.js
This implements a new build system for the browser using Browserify. All of the existing scripts are concatenated together, and then the result is run through browserify to bundle all of the modules. Over time, we would gradually convert the items in ```legacyModules```  to real modules that are loaded using ```require()```, and when everything is converted we could eventually just run browserify directly on ```default.js```.
@code-hunger I think this addresses what you mentioned regarding implementing features as modules. Does this approach make sense?
Once we decide on what the right approach is, I'll implement something similar for the webview bundle as well, and remove the old grunt-based system.
> New build system

- js/keybindings.js
- localization/languages/en-US.json
- main/main.js
Ctrl+Shift+D sounds a reasonable shortcut, D as for Duplicate
Cherry-picked from #615
> Add a Duplicate tab menu item. Fixes #400

- js/searchbar/hostsSuggestionsPlugin.js
- js/util/hosts.js
- js/util/urlParser.js
The hosts list are not exclusively bound to the urlParser. This way is more testable and reusable.
> Modularize hosts list generation

- js/api-wrapper.js
- js/keybindings.js
- js/searchbar/customBangs.js
- js/searchbar/openTabsPlugin.js
- js/sessionRestore.js
- js/tabState.js
- js/tabState/task.js
- js/taskOverlay/taskOverlay.js
- js/taskOverlay/taskOverlayBuilder.js
Rewrote it as a class. It has a mroe clear interface, with helpers for map/forEach/… on the inner `tasks[]` array (65ed6c4224fc742aaf0ef1ec5cb66b4bd06f5a7c), some optimizations (54ab215fbf9a53c3e56d3f8c83ad2edfa16330c8 - arr.map().indexOf() is inefficient, 013c01f9b2b5e2735cf42c8f9e16da2e272f0772 - no need to sort the whole array just to take the lowest value; here I've also ran `standard`, which made some extra styling changes), removed all direct references to the inner task array (helps us think about `tasks` as a *task list*, and not an *enhanced array of task objects* - 65ed6c4224fc742aaf0ef1ec5cb66b4bd06f5a7c), also rewrote some parts using the provided helpers to clean the code and avoid duplication (54ab215fbf9a53c3e56d3f8c83ad2edfa16330c8).
It got a bit longer than the previous …
> Convert the taskPrototype to a TaskList class

- ext/textColor/textColor.js
- js/api-wrapper.js
- js/deferredLoad.js
- js/navbar/tabColor.js
- js/webviews.js
- scripts/buildBrowser.js
@code-hunger Any suggestions?
I had to add an additional file, `deferredLoad.js`, that initializes the tabColor module. The reason for this is that in order to attach the events correctly, tabColor has to be initialized after the `webviews` object is created, but before the first view is created. I expect the solution to this is to convert webviews to a module and have tabColor depend on it, but that's going to require a bunch of other changes first.
> Convert tabColor to a module

- ext/abp-filter-parser-modified/abp-filter-parser.js
- js/filteringRenderer.js
- localization/languages/bn.json
- localization/languages/cs.json
- localization/languages/de.json
- localization/languages/en-US.json
- localization/languages/es.json
- localization/languages/fa.json
- localization/languages/fr-FR.json
- localization/languages/hu.json
- localization/languages/it.json
- localization/languages/ja.json
- localization/languages/ko.json
- localization/languages/lt.json
- localization/languages/pl.json
- localization/languages/pt-BR.json
- localization/languages/pt-PT.json
- localization/languages/ru.json
- localization/languages/tr_TR.json
- localization/languages/zh-CN.json
- localization/languages/zh-TW.json
- localization/localizationHelpers.js
- main/filtering.js
- pages/settings/index.html
- pages/settings/settings.css
- pages/settings/settings.js
This addresses most of #639:
* It adds a third content-blocking level (block only third-party ad and tracking requests), which will become the default in 1.9.
* It adds an option to disable content-blocking for a specific site.
Screenshot:
I think it looks a little cluttered - maybe separating the script and image options more clearly would help - but it should be OK for now.
Once this is merged, I'll change the default setting to third-party blocking in a separate PR.
> Add options to block third-party ads and add site exceptions

- js/searchbar/searchbarPlugins.js
- js/searchbar/updateNotifications.js
- localization/languages/ar.json
- localization/languages/bn.json
- localization/languages/cs.json
- localization/languages/de.json
- localization/languages/en-US.json
- localization/languages/es.json
- localization/languages/fa.json
- localization/languages/fr-FR.json
- localization/languages/hu.json
- localization/languages/it.json
- localization/languages/ja.json
- localization/languages/ko.json
- localization/languages/lt.json
- localization/languages/pl.json
- localization/languages/pt-BR.json
- localization/languages/pt-PT.json
- localization/languages/ru.json
- localization/languages/tr_TR.json
- localization/languages/zh-CN.json
- localization/languages/zh-TW.json
- pages/settings/index.html
- pages/settings/settings.js
- scripts/buildBrowser.js
With this PR, Min will automatically check for new updates after startup, and once a day while the browser is open. If an update is found, it will display a notification in the searchbar that links to the release notes:
The network requests to GitHub don't include any personally-identifying information (aside from an IP address), but in case of privacy concerns (or if you just don't want to be notified), I've also added an option to disable update checks to the settings page:
> Show a notification in the searchbar when a new version of Min is available

- js/searchbar/customBangs.js
- localization/languages/ar.json
- localization/languages/bn.json
- localization/languages/cs.json
- localization/languages/de.json
- localization/languages/en-US.json
- localization/languages/es.json
- localization/languages/fa.json
- localization/languages/fr-FR.json
- localization/languages/hu.json
- localization/languages/it.json
- localization/languages/ja.json
- localization/languages/ko.json
- localization/languages/lt.json
- localization/languages/pl.json
- localization/languages/pt-BR.json
- localization/languages/pt-PT.json
- localization/languages/ru.json
- localization/languages/tr_TR.json
- localization/languages/uk.json
- localization/languages/zh-CN.json
- localization/languages/zh-TW.json
I was getting annoyed having to manually open the task overlay, and mouse over to the trash icon to remove tasks. This custom bang just gets rid of tasks by name/number or the current if nothing is specified.
> custom bang for closing tasks

- js/dbMigration.js
- js/default.js
- js/navbar/bookmarkStar.js
- js/places/fullTextSearch.js
- js/places/places.js
- js/places/placesWorker.js
- js/util/database.js
- js/util/settings/settings.js
- main/main.js
With the current database schema, the URL is the primary key of each page, and the search index is a multi-entry index, where each word in the page is an entry. As far as I can tell, this means that for each word added to the search index, Chrome stores a new entry of word -> URL, which means that at least ```(length of URL) * size of search index``` worth of storage space is wasted unnecessarily.
As a result, the database gets large fairly quickly. Also, something about the way it is stored seems to cause Chromium to not fully remove everything when old items are deleted, which causes the database to continually grow in size.
To fix this, I've updated the schema to use an auto-incrementing ID as the primary key, with the URL as a secondary index. I expect the ID's are still duplicated, …
> Reduce storage space needed to store history

- css/tabBar.css
- css/tabEditor.css
- index.html
- js/browserUI.js
- js/default.js
- js/defaultKeybindings.js
- js/menuRenderer.js
- js/navbar/bookmarkStar.js
- js/navbar/tabBar.js
- js/navbar/tabEditor.js
- js/searchbar/bangsPlugin.js
- js/searchbar/bookmarkManager.js
- js/searchbar/searchbar.js
- js/searchbar/searchbarPlugins.js
- js/sessionRestore.js
- js/taskOverlay/taskOverlay.js
* Fixes #906 
* Makes the tab bar code a bit easier to understand by separating the editor from the tabs
* Since the new animations only use transforms and opacity changes, they should be a bit smoother
> Rewrite the tab open/close animation

- README.md
- package.json
- scripts/buildDebian.js
- scripts/createPackage.js
With 8GB RAM released, Raspbian has been renamed to Raspberry Pi OS.
https://www.raspberrypi.org/downloads/raspbian/
> Follow the changed OS name "Raspberry Pi OS".

- js/userscripts.js
Currently, only `include`, `matches`, and `exclude` are supported, but this should be enough to use at least a few basic scripts without modification.
> Partial Tampermonkey syntax support

- css/tabBar.css
- js/browserUI.js
- localization/languages/ar.json
- localization/languages/cs.json
- localization/languages/de.json
- localization/languages/en-US.json
- localization/languages/es.json
- localization/languages/fa.json
- localization/languages/fr-FR.json
- localization/languages/fr.json
- localization/languages/hu.json
- localization/languages/it.json
- localization/languages/ja.json
- localization/languages/ko.json
- localization/languages/lt.json
- localization/languages/pl.json
- localization/languages/pt-BR.json
- localization/languages/pt-PT.json
- localization/languages/ru.json
- localization/languages/tr_TR.json
- localization/languages/uk.json
- localization/languages/uz.json
- localization/languages/vi.json
- localization/languages/zh-CN.json
- localization/languages/zh-TW.json
With this change, focus mode will show all open tabs in the current task (instead of just the current one), and let you switch between them. You still can't switch tasks or create new tabs. This should hopefully make it useful in a wider range of situations.
> Show other tabs in focus mode

- js/browserUI.js
- localization/languages/ar.json
- localization/languages/bn.json
- localization/languages/cs.json
- localization/languages/de.json
- localization/languages/en-US.json
- localization/languages/es.json
- localization/languages/fa.json
- localization/languages/fr-FR.json
- localization/languages/fr.json
- localization/languages/hu.json
- localization/languages/it.json
- localization/languages/ja.json
- localization/languages/ko.json
- localization/languages/lt.json
- localization/languages/pl.json
- localization/languages/pt-BR.json
- localization/languages/pt-PT.json
- localization/languages/ru.json
- localization/languages/tr_TR.json
- localization/languages/uk.json
- localization/languages/uz.json
- localization/languages/vi.json
- localization/languages/zh-CN.json
- localization/languages/zh-TW.json
- pages/settings/index.html
- pages/settings/settings.js
From issue https://github.com/minbrowser/min/issues/1072
Allows the user to open a new tab and switch to it with CTRL+left.
I'm not quite sure what `disposition` refers to. And this should probably be a user preference instead of a direct change (which I'm not sure how to do).
> Add setting for opening tabs in foreground 

- main/UASwitcher.js
This is an attempt to fix #868, originally based on #893.
> Use Edge UA for google sign-in

- ext/filterLists/updateEasylist.js
- localization/languages/ar.json
- localization/languages/bg.json
- localization/languages/bn.json
- localization/languages/cs.json
- localization/languages/de.json
- localization/languages/en-US.json
- localization/languages/es.json
- localization/languages/fa.json
- localization/languages/fr.json
- localization/languages/hu.json
- localization/languages/it.json
- localization/languages/ja.json
- localization/languages/ko.json
- localization/languages/lt.json
- localization/languages/pl.json
- localization/languages/pt-BR.json
- localization/languages/pt-PT.json
- localization/languages/ru.json
- localization/languages/tr_TR.json
- localization/languages/uk.json
- localization/languages/uz.json
- localization/languages/vi.json
- localization/languages/zh-CN.json
- localization/languages/zh-TW.json
- main/filtering.js
- pages/settings/index.html
- pages/settings/settings.css
- pages/settings/settings.js
* Show a count of the requests blocked by Min:
* Add support for creating a `customFilters.txt` file that will be used in addition to the standard list (fixes #1200)
The "customize filters" link will go to a wiki article that I'll publish after the next release, which will include the Easylist license information and explain how to create custom filters.
One interesting issue is how custom filters interact with the existing filtering settings for the default list. Right now, if you add a custom filter but have "block third-party requests" set, your custom filter will only apply to third-party requests, which could be unexpected. We could ignore the settings for custom filters, but that might be confusing as well - e.g. if you add a site to the exception list, some resources on it could …
> Some content blocking improvements

- js/keybindings.js
Fixes issue #1231 
My approach simply discards "shift+" from the string that is being tested. I am not so experienced with regex so there is probably a better way to exclude shift+ instead of .replace.
> Fix: shift+letter not registering as single letter shortcut

- css/tabBar.css
- js/navbar/tabBar.js
- js/sessionRestore.js
- js/tabAudio.js
- js/tabState/tab.js
- js/util/keyMap.js
In response to Can't Mute Tab Issue #1221
This enables the user to mute a tab with a shortcut. By default it is `shift+mod+m`.
Whenever a tab has muted setting enabled it will show the muted icon next to the tab, even if the tab has no audio playing. The playing speaker icon will only show if a tab is playing audible audio. Otherwise, no icon is shown.
I did run into an issue with the icon being taller than the tab title. Not sure if we want to shrink the icon or keep at the same size as the other icons in the nav bar.
> Added shortcut to mute a tab

- css/tabBar.css
- js/navbar/tabBar.js
- localization/languages/ar.json
- localization/languages/bn.json
- localization/languages/cs.json
- localization/languages/de.json
- localization/languages/en-US.json
- localization/languages/es.json
- localization/languages/fa.json
- localization/languages/fr.json
- localization/languages/hu.json
- localization/languages/it.json
- localization/languages/ja.json
- localization/languages/ko.json
- localization/languages/lt.json
- localization/languages/pl.json
- localization/languages/pt-BR.json
- localization/languages/pt-PT.json
- localization/languages/ru.json
- localization/languages/tr.json
- localization/languages/uk.json
- localization/languages/uz.json
- localization/languages/vi.json
- localization/languages/zh-CN.json
- localization/languages/zh-TW.json
- pages/settings/index.html
- pages/settings/settings.js
It was quite hard for me to see how many tabs I had open so I added a light divider between the tabs to improve that contrast.
**Before**
**After**
If this doesn't suit the idea of having a minimalistic browser I could probaly make this an optional feature in the users preferences.
Let me know what you think 😁
> Add a light divider between tabs to increase contrast

- localization/languages/de.json
There were some keys missing which were present in the [en-US.json](https://github.com/minbrowser/min/blob/master/localization/languages/en-US.json#L239) starting at line 239 to the end of the file, which I added.
I also changed some translations which were already present, because I thought that I have found a better translation and also because of consistency.
This is my first time making a pull request. Did I miss something?
> Add German Translations

- package.json
'.' is not recognized as an internal or external command, operable program or batch file.
This seems to be fixed by adding escaped quotation marks.
This is the same fix as proposed in the PR https://github.com/minbrowser/min/pull/1236
> npm run start path not recognized

- package.json
Hello! I know this was previously "fixed" - but it wasn't. 
This changes using `node_modules/.bin/concurrently` *just an example* to using `concurrently` *still an example*
This allows all scripts to be ran on windows now but requires that you have to have the NodeJS path variable configured correctly.
Thanks! 🎉
> update package json scripts

- package.json
fix start script
this was a bug on windows where it couldn't find the parents directory /concurrently, for example:
Min: GitHub/Min
Cannot find GitHub/concurrently/bin/concurrently.js
Well this fixes it, just by removing some quotes, out of every thing I've tested - everything on linux and macOs still work
> fix concurrently scripts

- js/menuRenderer.js
- main/main.js
- main/touchbar.js
- scripts/buildMain.js
Fixes #335.
I kept the available actions pretty simple now, basically just the same actions as what's in the tab bar:
I don't actually have a touchbar to test this on (just the simulator), so I don't have a good sense of what would be useful, but if anyone has more ideas, let me know.
(The biggest one is probably showing a list of open tabs, but it's reasonably complicated to send the tab list to the parent process to do that, so I want to skip doing that for now).
> Add basic touchbar support

- docs/statistics.md
- js/default.js
- js/statistics.js
- localization/languages/ar.json
- localization/languages/bg.json
- localization/languages/bn.json
- localization/languages/cs.json
- localization/languages/de.json
- localization/languages/en-US.json
- localization/languages/es.json
- localization/languages/fa.json
- localization/languages/fr.json
- localization/languages/hu.json
- localization/languages/it.json
- localization/languages/ja.json
- localization/languages/ko.json
- localization/languages/lt.json
- localization/languages/pl.json
- localization/languages/pt-BR.json
- localization/languages/pt-PT.json
- localization/languages/ru.json
- localization/languages/tr.json
- localization/languages/uk.json
- localization/languages/uz.json
- localization/languages/vi.json
- localization/languages/zh-CN.json
- localization/languages/zh-TW.json
- pages/settings/index.html
- pages/settings/settings.js
This PR adds a way to collect usage statistics, which allows us to answer questions like "How many users does Min have?", and "which operating systems are most frequently used?". Eventually, this can also be expanded to include things like "How often is feature X used?", which should make it easier to prioritize what to work on.
I'm going to start writing a document soon that describes what's collected in more detail (which will be linked to from the settings page), but in summary:
* We won't collect anything that can be used to identify individual users.
* We won't collect any browsing history, passwords, or other data stored in Min.
* There's an option to opt-out on the settings page.
Todo:
> Add usage statistics collection

- css/base.css
- pages/settings/index.html
- pages/settings/settings.css
- pages/settings/settings.js
Note: Spellcheck **should** be disabled by default for textarea, but I think it's safer to include in case it ever changes.
Fixes #1427
> Added textarea for ads and trackers whitelist in settings

- js/util/settings/settings.js
- js/util/settings/settingsContent.js
- pages/settings/settings.js
- reader/readerThemeSelector.js
Fixes #1520 
`settings.set` can be called from either the main process or the UI process. Previously, calling this would just write to the settings file immediately from whichever process it was called in. The problem with this is that if `settings.set` is called multiple times in a sequence, multiple `fs.writeFile` calls can happen at the same time, which corrupts the settings file.
This PR makes two changes to avoid that:
* Save requests are forwarded from the UI process to the main process, so that `writeFile` is only called from the main process.
* Within the main process, `writeFile` calls are queued so that they can't occur simultaneously.
> Fix data corruption when modifying multiple settings simultaneously

- css/windowControls.css
- main/main.js
- pages/settings/index.html
- pages/settings/settings.js
As a Mac user, the only way to "maximize" a window is to double click on the title bar of the application. **However, it's not possible to do it with Min browser since title bar is hidden on Mac.** 
Although @PalmerAL [kindly point out](https://discord.com/channels/764269005195968512/764544014259060797/814756935316013066) that I can hold "cmd" + clicking on the "green traffic light", it's not as intuitive as double clicking title bar, as most users should be familiar with. 
Also, if we are giving Linux users that have special desktops the option to show title bar, why wouldn't we make it consistent for all platforms and give users flexibility of having a separate title bar? 
I therefore propose to enable "Use separate title bar" option for all platforms.
This commit also adjust the …
> Enable "use separate title bar" setting for all platforms (not just Linux)

- js/passwordManager/passwordCapture.js
- js/preload/passwordFill.js
See discussion for context: https://github.com/minbrowser/min/commit/80d69f186c04c49dda8b84dae3f7cecc58ce2a82#commitcomment-49226470
Main change here is to try to identify a single "best" username field on a page to autofill, rather than autofilling every field that could be a username. This improves the situation on some pages, but also increases the risk of broken autofill (if the field we identify as "best" isn't the right one).
> Autofill improvements

- css/bookmarkManager.css
- css/listItem.css
- js/navbar/bookmarkStar.js
- js/places/places.js
- js/places/placesWorker.js
- js/searchbar/bookmarkEditor.js
Previously, clicking on the bookmark star or pressing ctrl+d while on a page you already bookmarked would delete the bookmark. There were two problems with this:
* If you didn't remember whether you'd bookmarked the page, but wanted to bookmark it, pressing ctrl+d would sometimes do the opposite of what you wanted (by deleting the bookmark).
* Once you'd bookmarked a page, there wasn't an easy way to edit the bookmark's tags without going to the bookmark viewer.
This PR changes the behavior so that clicking the star or using the shortcut will always save the page and open the bookmark editor, regardless of whether it was previously bookmarked. The editor now has a separate button to delete the bookmark:
> Change bookmark editor behavior

- main/remoteActions.js
Mostly fixes #1662 (which also has an explanation of why this is necessary).
This is still broken if you maximize/unmaximize the window by dragging on the title bar, rather than clicking the buttons. We could possibly solve that by watching for `resize` events and sending maximize/unmaximize based on that, but I doubt it would work reliably.
> Send maximize/minimize/unmaximize events to work around electron issue

- css/windowControls.css
- localization/languages/ar.json
- localization/languages/fa.json
- localization/localizationHelpers.js
Fixes #1688.
This still isn't perfect (and the layout isn't really RTL), but it's at least usable now.
> Fix mac titlebar layout for RTL languages

- js/default.js
- js/pageTranslations.js
- js/preload/translate.js
- js/remoteMenuRenderer.js
- js/webviewMenu.js
- main/remoteMenu.js
- scripts/buildPreload.js
This PR adds an in-browser page translation feature using [LibreTranslate](https://github.com/LibreTranslate/LibreTranslate), an open-source translation engine, available in the page context menu.
This is discussed more in #1180, but the intent is to include this as an experimental feature (with a "beta" label in the UI), and see how many people use it. If it gets significant usage, there's options for improving the translation quality, running LibreTranslate on better hosting to improve the translation speed, etc.
> Add in-browser translation

- js/preload/siteUnbreak.js
- main/UASwitcher.js
Starting a few days ago, Gmail now checks (for unknown reasons) for `navigator.userAgentData`. If it isn't found, it redirects to the basic HTML version.
Client hints currently doesn't work in Electron: https://github.com/electron/electron/issues/30201. So this PR adds a (somewhat ridiculous) workaround of creating a fake `userAgentData` object that mostly conforms to the one Chrome provides. With that, the standard version of Gmail seems to load again.
Separately, signing in to Gmail is broken, see https://github.com/minbrowser/min/issues/868. You can workaround that by setting your user-agent to Firefox in preferences, but then you'll have to switch back to the standard user-agent after signing in before trying this fix.
I wish Google would stop trying to block non-official Chromium …
> Implement partial UA client hints support for gmail

- main/UASwitcher.js
This PR switches Google sign in to use a Firefox UA rather than an edge one. To avoid having to update the UA on every Firefox release, it uses the current date to guess what the latest Firefox version is.
#868
> Use Firefox UA for google accounts

- scripts/buildLocalization.js
This PR fixes several issues:
* `decomment(data)` used to be called twice in case of an error. Since it is called at least once, we assign the result to a variable
* `String.prototype.match` is ~15 times faster than `RegExp.prototype.exec` (and is generally recommended to use `match` if only one match is needed, like in this case)
* There is no need for the `g` flag on the regex
* In case of missing closed brace (like it was the case with `tr.json`), the entire build would fail, because `exec(e)[1]` was not checking for `null` and the actual error message was `Unexpected end of JSON input`
* `exec(e)` was converting the entire error (including the stack trace) to a string. It might happen that somehow `at position` appears somewhere in the stack trace, while the error message is …
> Improve error handling for invalid JSON

- css/taskOverlay.css
- index.html
- js/taskOverlay/taskOverlay.js
- localization/languages/ar.json
- localization/languages/bg.json
- localization/languages/bn.json
- localization/languages/cs.json
- localization/languages/de.json
- localization/languages/en-US.json
- localization/languages/es.json
- localization/languages/fa.json
- localization/languages/fr.json
- localization/languages/hu.json
- localization/languages/it.json
- localization/languages/ja.json
- localization/languages/ko.json
- localization/languages/lt.json
- localization/languages/pl.json
- localization/languages/pt-BR.json
- localization/languages/pt-PT.json
- localization/languages/ru.json
- localization/languages/tr.json
- localization/languages/uk.json
- localization/languages/uz.json
- localization/languages/zh-CN.json
- localization/languages/zh-TW.json
This PR adds a search box to the top of the task overlay to search through open tabs. Pressing enter from within the search switches to the first result.
I'm not totally happy with the way the search input looks; if anyone has ideas for how to make it better, let me know. The first search result should also probably be highlighted so that it's clear you can select it with enter.
> Add search input to task overlay

- js/util/theme.js
- localization/languages/ar.json
- localization/languages/bg.json
- localization/languages/bn.json
- localization/languages/cs.json
- localization/languages/de.json
- localization/languages/en-US.json
- localization/languages/es.json
- localization/languages/fa.json
- localization/languages/fr.json
- localization/languages/hu.json
- localization/languages/it.json
- localization/languages/ja.json
- localization/languages/ko.json
- localization/languages/lt.json
- localization/languages/pl.json
- localization/languages/pt-BR.json
- localization/languages/pt-PT.json
- localization/languages/ru.json
- localization/languages/tr.json
- localization/languages/uk.json
- localization/languages/uz.json
- localization/languages/vi.json
- localization/languages/zh-CN.json
- localization/languages/zh-TW.json
- main/main.js
- pages/settings/index.html
- pages/settings/settings.js
Adds the option to let the darkmode setting rely on the underlying OS darkmode.
Only tested on Mac.
---
I'm also not familiar with Electron and how these apps are usually structured. I read through the Min architecture document on the wiki but could only get this to work by grabbing the OS setting from the main thread.
> Add option to follow system darkmode

- localization/languages/de.json
settingsEnableDarkMode: "Dunkelmodus" isn't used in the german language changed to the more common Nachtmodus (Nightmode)
settingsDarkModeSystem: Added Translation (directly translates to "Use System-Colors")
settingsUserAgentToggle: Fixed Grammar
settingsDDGExplanation: Fixed Grammar
openReaderView: Fixed Grammar according to context
autoRedirectBannerReader: Fixed Grammar according to context
settingsPasswordAutoFillHeadline: Fixed Grammar
settingsSelectPasswordManager: Fixed Grammar
passwordManagerSetupSignIn: Fixed Grammar; Fixed Typo
passwordManagerUnlock: Fixed Grammar; Changed "Hauptkennwort" to "Masterpasswort" because it's more common
clickToCopy: Added Translation
copied: Added Translation
> Missing translations; Fixed Grammar; Common Words

- main/remoteActions.js
I was reading [an article](https://popzazzle.blogspot.com/2021/10/min-browser-can-you-resist-irresistible.html) on Min that mentioned that some cookies remained after using the "clear history" command. I spent some time investigating this, and found a few issues:
* Loading favicons can store cache and cookie data, but we were never clearing this data, since it's stored in a different partition than regular web content.
* We weren't calling `clearCache` in addition to `clearStorageData`, which is needed to empty the cache directory.
* Using `origin: 'http://'` results in IndexedDB databases not being cleared (I'm not sure why); switching to just `clearStorageData()` with no origin parameter set fixes this.
* We can't do this in the default session, since that would delete Min's history …
> Fix several problems with clearing history

- js/passwordManager/keychain.js
- main/keychainService.js
This PR changes the way passwords are stored with the built-in password manager. Previously, the `keytar` module was used to add individual passwords as keychain entries; however, as described in #1761, the keytar module is no longer being updated and will stop working in future versions of node/electron, so we need an alternative solution.
With this PR, passwords are instead stored in a file inside the app data directory, which is encrypted using a randomly-generated key that's stored in the keychain. The encryption and decryption is all handled by the recently-added safeStorage module in Electron: https://www.electronjs.org/docs/latest/api/safe-storage
The behavior of the password manager should be identical with these changes - previously-saved passwords should get automatically …
> Replace keytar with the built-in safeStorage module

- js/passwordManager/bitwarden.js
- js/passwordManager/keychain.js
- js/passwordManager/managerSetup.js
- js/passwordManager/onePassword.js
- js/util/process.js
- localization/languages/ar.json
- localization/languages/bg.json
- localization/languages/bn.json
- localization/languages/cs.json
- localization/languages/de.json
- localization/languages/en-US.json
- localization/languages/es.json
- localization/languages/fa.json
- localization/languages/fr.json
- localization/languages/hr.json
- localization/languages/hu.json
- localization/languages/it.json
- localization/languages/ja.json
- localization/languages/ko.json
- localization/languages/lt.json
- localization/languages/pl.json
- localization/languages/pt-BR.json
- localization/languages/pt-PT.json
- localization/languages/ru.json
- localization/languages/tr.json
- localization/languages/uk.json
- localization/languages/uz.json
- localization/languages/vi.json
- localization/languages/zh-CN.json
- localization/languages/zh-TW.json
This PR attempts to fix a few of the most common issues with the Bitwarden integration:
* Bitwarden recently started requiring an API key instead of a password in some cases: https://bitwarden.com/help/article/cli-auth-challenges/, which I believe is the cause of the recent issues about Bitwarden setup failing. This PR updates the installation flow to ask for a client ID and key instead of a username and password. This also makes it possible to connect Bitwarden accounts that have 2FA enabled.
Fixes #1796, #1394, #929
* Added a re-prompt for authentication if the user is signed out and tries to autofill a password. Previously, the authentication prompt would never show after setup was complete, which meant it was possible to end up in a state where you weren't signed in and there was no …
> Improve Bitwarden integration

- js/places/fullTextSearch.js
- js/places/placesWorker.js
- js/searchbar/placesPlugin.js
- js/util/database.js
Often when searching using the full-text search feature, the page title alone isn't enough to tell whether the result is what I'm looking for. This PR shows a small snippet of the page text that matches the query below the result, which makes it easier to figure out. An example:
This also brings back storage of the full page text, instead of just the tokenized index. This was originally removed to save storage space; however, I believe the main problem that was originally causing the database to use excessive space is now fixed (#832), so this hopefully shouldn't be too much of a problem.
> Add a snippet to full-text search results

- package.json
- pages/pdfViewer/viewer.css
- pages/pdfViewer/viewer.js
This PR adds the necessary code (mostly adapted from the default pdfjs viewer) to support internal / external links.
Test page: https://www.antennahouse.com/hubfs/xsl-fo-sample/pdf/basic-link-1.pdf?hsLang=en
The PDF viewer code is pretty messy; I didn't change any of it in this PR, but might come back to it later.
Fixes #1422, https://github.com/minbrowser/min/issues/909#issuecomment-1007962847
> Support links in PDF viewer

- js/util/theme.js
- main/main.js
- main/themeMain.js
- scripts/buildMain.js
This PR update the theme settings to use Electron's [nativeTheme](https://www.electronjs.org/docs/latest/api/native-theme) module. This means that the theme settings in Min's preferences will also control whether webpages and context menus use a dark mode - previously, this was always determined by the OS global theme setting.
> Improve integration of browser theme settings with system theme

- css/tabBar.css
- css/windowControls.css
- js/keybindings.js
- js/navbar/tabBar.js
- package.json
Implements the rest of https://github.com/minbrowser/min/issues/948#issuecomment-670179504. Normal dragging with the mouse moves the window (same as the current behavior). Dragging while holding the cmd key rearranges tabs.
The Dragula library has a hard-coded check that ignores drag events while cmd is pressed: https://github.com/bevacqua/dragula/blob/master/dragula.js#L98, so to make this work, I've forked the library and switched the dependency in Min to use the forked version instead.
> Support tab dragging on macOS

- scripts/buildDebian.js
While trying to install the browser on Debian based distributions like Ubuntu and Zorin OS, I came across the dependency error stating that the libsecret-1-dev package was not found.
In other projects I participate in, by default we don't send dev packages to build in production.
This PR fixes the catch below.
Congratulations on the project, it is very useful.
> fix: change libsecret-1-dev to libsecret-1-0 for build debian

- scripts/createPackage.js
Fixes #2073
@Harsith-Panda can you confirm this works?
After checking out the branch, you'll need to build a package with `npm run buildMac[Intel/Arm]`
> Enable Gatekeeper support on macOS

- localization/languages/es.json
Fix the Spanish translation for `email`.
> Fix Spanish translation for `email`

- README.md
Using `pacman -Sy <package>` in Arch Linux distributions is dangerous as it can lead to dependency mismatches and a "partial upgrade".   
using `pacman -S <package>` is the correct process, or if you want to update to the latest versions, using the full upgrade command, `pacman -Syu <package>` will update all packages and install the latest version of your package    
https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported
> remove dangerous pacman -Sy command for arch linux install

- css/windowControls.css
- index.html
- package.json
In Electron 24, we can't have a region that is both draggable and clickable: https://github.com/electron/electron/issues/37789. This makes it impossible to drag the window on macOS with the existing titlebar design.
Windows and Linux currently have the same limitation; we solve it there by shifting the titlebar down and adding empty space above (see previous discussion: https://github.com/minbrowser/min/issues/630). But no other apps do the same thing on macOS, so it would look odd to do it there.
My current idea (which this PR implements) is to do this, where the draggable regions are in red:
Although the space to the right of the window controls looks slightly odd, and it's not obvious what's draggable:
If anyone has feedback or other ideas, please let me know!
> Modify Mac draggable region for Electron 24

- main/download.js
- pages/pdfViewer/viewer.js
URLs that contain "#pdfjs.action=download" was opening Electron's built-in pdf viewer.
To reproduce, open https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf#pdfjs.action=download
This also fixes #2208.
> Remove "#pdfjs.action=download"

- js/passwordManager/onePassword.js
in case if users do not have `op` in their $PATH
> fix 1Password autofill not working

- js/places/placesSearch.js
- js/places/placesService.html
- js/places/placesService.js
- js/searchbar/openTabsPlugin.js
- package.json
From my testing, this module seems to produce higher-quality results, particularly for history search, than the old string-score module.
I also adjusted some of the filtering logic to do fuzzy matching against a better set of URLs.
> Switch to quick-score for fuzzy search

- css/taskOverlay.css
- js/taskOverlay/taskOverlay.js
- js/taskOverlay/taskOverlayBuilder.js
- package.json
Selecting multiple tabs works by holding Cmd (Mac) or Ctrl (Windows/Linux) and clicking.
https://github.com/minbrowser/min/assets/10314059/0226a8ac-f28b-4201-96db-a16e0e368a1a
At some point, I plan to implement this for the tab bar also (which will require switching from Dragula to SortableJS there as well).
> Implement multi-select for rearranging tabs in task overlay

- js/searchbar/customBangs.js
I think you might have left this behind when you were working on [this PR](https://github.com/minbrowser/min/pull/2342) I noticed it because the fuzzy finding functionality using `!task` was not working anymore. I also noticed in that PR you changed the score target from .4 to .35, I was not sure wether it was necessary here so I did not do it for now. One last thing I am not sure that the `require` statement is in the right place but if it isn't I can move it where you prefer.
This is my first time contributing to Min I hope I did everything according to your requirements.
> Switch to quick-score for fuzzy search (leftover)

- js/webviews.js
- main/viewManager.js
Previously, "block scripts" filtered requests at the network level by content type, which meant inline scripts weren't being blocked. This sets `javascript: false` on the webContents, which truly disables all JS.
We still need JS for the browser internal pages (settings/reader/PDF viewer), so this checks the URL on each navigation and re-creates the view with an updated preference value if necessary.
Fixes #2382.
> Improve the "block scripts" setting

- css/tabBar.css
- js/navbar/tabBar.js
This PR makes a couple of improvements to the tab bar:
* When you hover over the current tab, the domain is displayed. I'm hoping this does two things:
* It makes it a bit easier to check what site you're currently on, which helps with eg. phishing
* It provides more of a hint that you can click on the tab to get to the URL bar
* <img src="https://github.com/minbrowser/min/assets/10314059/440a3e1e-747d-462d-845b-49ab9b75a3d6" width="400"/>
* The current tab now has a larger minimum width than the other tabs.
* At the old minimum width, it was difficult to fit the title and the controls in; this gets worse when we show a URL, since there usually isn't room to fit the complete domain.
* When the ratio of (window width / tab count) drops below a threshold, the font size for the tab titles is …
> Tab bar UI updates

- js/bookmarkConverter.js
On Windows (not sure about other OS), users are not able to import their old bookmarks from other browsers like Edge (haven't tried on Firefox). 
Ref #2444 
This patch fixes that issue. Now I can import and search through my bookmarks
> Fix: bookmarks data not being updated after importing

- README.md
The [min](https://aur.archlinux.org/packages/min)  is still on 1.30 and also using electron24.
Due to the current lifescycle of Arch Linux it is now using electron29 which ends up in having to compile electron24 from source.
This requires compiling Chromium then which is nearly 30 GB of downloading only and not mentioning the amount of time it would take to compile.
Instead this [min-browser-bin](https://aur.archlinux.org/packages/min-browser-bin) is up to date and also solves the issue as it compiles it from the `.deb` file provided which makes it take about a minute only.
> fix(arch):change aur pkg

- localization/languages/fr.json
This PR introduces new French translations for various user interface settings. 
- Added translations for:
- "Past and Match Style" ;
- "Language" ;
- Interface settings ;
- "Invert Page Colors" in the PDF viewer ;
- and other minor translation updates.
This PR continues the work of translating the Min browser's user interface into French, enhancing accessibility and usability for French-speaking users.
None
Feel free to reach out if you have any questions or need further adjustments. Thank you for considering these updates!
> feat(i18n): add French translations for user interface settings

- js/places/fullTextSearch.js
- js/places/places.js
- js/searchbar/placesPlugin.js
- js/util/urlParser.js
This uses the [text fragment API](https://developer.mozilla.org/en-US/docs/Web/URI/Fragment/Text_fragments) to generate a fragment based on the search query; Chromium will then try to scroll to the correct place in the page when the URL is opened.
This may not work in all cases (eg for certain combinations of special characters it may fail), but it works on the pages I've tested so far.
https://github.com/user-attachments/assets/8fd7b216-10df-4695-b3a2-5392f9812efb
> Scroll to query when opening full-text search result

- js/navbar/tabEditor.js
- js/searchbar/bangsPlugin.js
- js/searchbar/calculatorPlugin.js
- js/searchbar/instantAnswerPlugin.js
- js/searchbar/openTabsPlugin.js
- js/searchbar/placeSuggestionsPlugin.js
- js/searchbar/placesPlugin.js
- js/searchbar/searchSuggestionsPlugin.js
- js/searchbar/searchbar.js
- js/searchbar/searchbarPlugins.js
- js/searchbar/shortcutButtons.js
- js/searchbar/updateNotifications.js
...by using `input` rather than `keydown`. This should solve some bugs with text input - for example, pasting text or picking a character with an IME now updates the results correctly.
> Improve searchbar keyboard event handling

- js/sessionRestore.js
- js/util/settings/settingsMain.js
- package.json
- scripts/buildBrowser.js
Recently, there's been a couple reports of Min losing session restore data unexpectedly (#2519, #2527, also #2503 and https://discord.com/channels/764269005195968512/764544014259060797/1305916870473547776 which may or may not be related).
I'm not currently sure what the cause(s) of these are, as nothing has changed recently in this code, but this PR updates session restore to write the file atomically, which should mean that we can always re-launch with a valid restore file even if something goes wrong during the write. I also added some metrics collection for write failures and restoration failures to try to understand if this is a widespread issue.
It's possible that this is slower than a standard write, which mainly impacts shutdown times, as we write the file synchronously before …
> Use atomic writes for session restore

- js/searchbar/developmentModeNotification.js
- main/main.js
- main/menu.js
* Added an option to open the devtools for the places service, which might help with debugging #2503.
* Changed the browser devtools options to appear only when Min is run with the `--debug-browser` argument, or with the existing `--development-mode`.
* Having these options appear during regular usage is somewhat confusing (it's possible to get mixed up between the browser devtools and the page devtools), and also a potential source of security issues - if someone can be convinced to paste malicious code into the browser devtools, the consequences are quite bad. I don't know of any specific instances of this happening, but it seems worthwhile to address preemptively.
Normal mode:
Debug mode:
> Update the browser debugging menu

- js/tabState/tab.js
- js/util/settings/settingsMain.js
- js/webviews.js
- main/download.js
- main/main.js
- main/menu.js
- main/viewManager.js
- main/windowManagement.js
- package.json
BrowserView is deprecated in Electron; this PR moves to the essentially equivalent replacement.
> Migrate from BrowserView to WebContentsView

- index.html
- js/keybindings.js
- js/searchbar/bookmarkEditor.js
- js/taskOverlay/taskOverlayBuilder.js
- main/main.js
- package.json
- pages/settings/settings.js
> Remove mousetrap; allow creating shortcuts containing the super key

- css/passwordViewer.css
- index.html
- js/passwordManager/keychain.js
- js/passwordManager/passwordViewer.js
- localization/languages/en-US.json
- localization/languages/nl.json
- main/keychainService.js
- package.json
Allows you to import / export credentials from the built-in password manager.
It will import / export using the same schema the built-in password manager uses to store the credentials which is the following:
```json
{
"version": 1,
"credentials": [
{
"domain": "google.com",
"username": "Google User",
"password": "123456"
},
{
"domain": "github.com",
"username": "Github User",
"password": "123456"
}
]
}
```
Currently it will only let you import if you have 0 passwords and only export if you have more than 1 password. We might want to do some merge thing but I didn't want to do that yet since that could go a couple ways, e.g. override, merge.
Also refactored some "render to dom" functionality into separate functions.
Let me know what you think.
> Can import / export credentials from built-in password manager

- localization/languages/sr.json
Hello @PalmerAL , I'm glad to have a chance to contribute to your project.
I'm currently working on translating the [official React documentation](https://github.com/reactjs/sr.react.dev) to Serbian, but I also contributed with translations to few other open-source projects.
My change here was mainly in using cyrillic instead of latin version of Serbian language introduced in #1914. Cyrillic is formal and it's used in all legal papers, so I thought it should be used here as well.
If I understood [Chromium](https://source.chromium.org/chromium/chromium/src/+/main:ui/base/l10n/l10n_util.cc) well, they don't differentiate Serbian cyrillic and latin versions, right? If I'm missing something, please tell me how to name latin file to have both versions available.
Hey @pvlvukovic, since I'm …
> Improve Serbian language
