minbrowser/min

Gruntfile.js, package.json
These are the same as Firefox.
=> Adds debian build categories and mime types

main.build.js, main/main.js
Windows Icon fixed in main.js as per request
=> Windows Icon Fix

main.build.js
Added min icon instead of default electron icon on Windows (Issue #86)
=> windows icon

Gruntfile.js
Adding missing information for Debian package.
=> Update debian package information, fix #111

css/navbarTabs.css
fixes https://github.com/PalmerAL/min/issues/70
=> Styled scrollbar for the tab bar

js/navbar/navbarTabs.js
Fixes #40 
@PalmerAL Did ```tabId``` exist on purpose and is there a difference to ```data.id```?
=> Close tabs with mouse middle click

js/webviewMenu.js
This allows the user to download the image.
**Warning**: it does not keep the image **name** and **extension**.
Any idea to improve this is welcome.
=> Add save option on image right click

Gruntfile.js, js/keybindings.js, js/util/defaultKeyMap.js, js/util/settings.js, main.build.js, main/main.js, pages/settings/index.html, pages/settings/settings.css, pages/settings/settings.js
This PR is adding a basic KeyMap customization support.
Changed the "Privacy Settings" to "Settings" and added the KeyMap Settings section
The key combinations are stored with the user settings.
This is a great project, thank you @PalmerAL !
=> Add basic KeyMap customization support

js/util/defaultKeyMap.js
"Add Task" keybinding is part of the application menu and cannot be customised for now
=> Remove wrong keyMap setting

js/webviewMenu.js
Download files & html pages on links from the context menu. Not enables on images because 'Save image' is already implemented
=> Added Save Link As to context menu

main.build.js, main/main.js
This allows users to toggle full screen with F11.
=> Add option to switch full screen

main.build.js, main/main.js, package.json
Same as path.join(app.getPath('appData'), packageJson.productName) by
default.
=> Use app.getPath('userData') for configuration files

main/main.js
=> macOS dock menu

css/searchbar.css, js/bookmarksHistory/bookmarksHistory.js, js/bookmarksHistory/placesSearch.js, js/bookmarksHistory/placesWorker.js, js/navbar/navbarTabs.js, js/readerview.js, js/searchbar/bangsPlugin.js, js/searchbar/customBangs.js, js/searchbar/searchSuggestionsPlugin.js, js/searchbar/searchbar.js
=> Implement search suggestions for custom bangs

localization/languages/es.json
=> Update es translation

localization/languages/hu.json
added the missing strings and their translations
=> added the missing strings

css/webviews.css, index.html, js/webview/swipeEvents.js, js/webviews.js, localization/languages/ja.json
I just filled missing translation and fixed some very small translation error and added horizontal swipe gestures indicators like chrome
=> Update ja.json & Swipe gestures indicators

js/default.js, localization/languages/pl.json
+ Polish translation
+ disabled browser interface zoom on macOS (double tap on Magic Mouse)
=> Polish translation + zoom fix

README.md
=> Improve Developing instructions in the README file

Gruntfile.js, js/webview/swipeEvents.js
=> Fix incorrect scrolling on mod + scroll zoom

js/util/database.js, localization/languages/cs.json, localization/languages/de.json, localization/languages/en-US.json, localization/languages/es.json, localization/languages/fr-FR.json, localization/languages/hu.json, localization/languages/ja.json, localization/languages/pl.json, localization/languages/pt-BR.json, localization/languages/pt-PT.json, localization/languages/ru.json, localization/languages/zh-CN.json
Let me know if this makes sense or if there's a better way.
The problem would be that it doesn't show up directly on start, but most probably before a db related issue like incomplete preferences screen or unable to connect to an URL:
Fixes #526
=> Add alert for multiple running instances of Min

README.md, package-lock.json, package.json
=> Improve npm management

localization/languages/zh-CN.json, localization/languages/zh-TW.json
corrected grammar mistake and complete all of the translation of simplified chinese language and added traditional chinese language
=> Corrected Simplified Chinese and added Traditional Chinese language

css/tabBar.css, js/webviews.js
This makes the back button transparent when you can't go back because you're on the first page.
=> Disable back button when it's not active

localization/languages/zh-TW.json
I think zh-TW.json is a copy from zh-CN, just changed the simplified words to the traditional words, so I modified to the 'real' Traditional Chinese and fix the grammar.
Sorry for my poor English!
=> fix zh-tw translation

localization/languages/fa.json
This commit adds Persian (Fa) localization to the project
=> Added Persian localization

localization/languages/it.json
🇮🇹 Adding an Italian localization to Nim. :-)
=> Add Italian translation

localization/languages/zh-TW.json
Since Min has updated to 1.9.0, there's something new to translate, so I updated the zh-TW translation file and modified some text to make the meaning more complete.
=> update zh-TW translation

localization/languages/fr-FR.json
Here´s my contribution, thanks for this browser !
=> An updated and corrected french translation

js/contextMenu.js, js/default.js, js/navbar/tabBar.js, localization/languages/ar.json, localization/languages/bn.json, localization/languages/cs.json, localization/languages/de.json, localization/languages/en-US.json, localization/languages/es.json, localization/languages/fa.json, localization/languages/fr-FR.json, localization/languages/fr.json, localization/languages/hu.json, localization/languages/it.json, localization/languages/ja.json, localization/languages/ko.json, localization/languages/lt.json, localization/languages/pl.json, localization/languages/pt-BR.json, localization/languages/pt-PT.json, localization/languages/ru.json, localization/languages/tr_TR.json, localization/languages/uk.json, localization/languages/zh-CN.json, localization/languages/zh-TW.json, localization/localizationHelpers.js
Added some words when "Missing translation" was said in comments
Modified some words, in accordance with what i often see in modern web browsers
#753
=> [WIP] ✨feat (adress bar input): implements context menu (copy, cut, paste, …  …select all, undo,redo)

localization/languages/vi.json
My Vietnamese isn't the best but hopefully this is good :)
=> Create Vietnamese translation

localization/languages/it.json
+ Added all missing translations for italian language
+ Minor adjustments to existing translations
=> Italian Translation Update (Native Speaker)

resources/postinst_script
=> Remove blocking prompt from upgrade script

localization/languages/vi.json
Updating the Vietnamese translation with new strings :upside_down_face:
=> Update Vietnamese translation

localization/languages/ko.json
- **Password Manager** has been added.
- **Task** has been shortened.
=> Update Korean strings.

css/tabBar.css, js/navbar/permissionRequests.js, js/navbar/tabBar.js, main/permissionManager.js, main/viewManager.js
=> Implement permissions support

localization/languages/uz.json
=> Added uzbek language

js/passwordManager/managerSetup.js, localization/languages/en-US.json
Tested on OSX with a privileged user. Need to check with a normal user before merging.
=> Implement auto-launching installer for password tool.

localization/languages/ko.json
=> Update Ko strings.

localization/languages/ar.json, localization/languages/bn.json, localization/languages/cs.json, localization/languages/de.json, localization/languages/en-US.json, localization/languages/es.json, localization/languages/fa.json, localization/languages/fr-FR.json, localization/languages/fr.json, localization/languages/hu.json, localization/languages/it.json, localization/languages/ja.json, localization/languages/ko.json, localization/languages/lt.json, localization/languages/pl.json, localization/languages/pt-BR.json, localization/languages/pt-PT.json, localization/languages/ru.json, localization/languages/tr_TR.json, localization/languages/uk.json, localization/languages/uz.json, localization/languages/vi.json, localization/languages/zh-CN.json, localization/languages/zh-TW.json, reader/index.html, reader/reader.js, reader/readerContent.css, reader/readerThemeSelector.js, reader/readerUI.css
Reading mode
*Adding translation
*Other small adjustments
=> Changes in Reading mode

css/taskOverlay.css, js/taskOverlay/taskOverlayBuilder.js
=> Show favicons for collapsed tasks

localization/languages/pt-PT.json
=>  fix syntax pt-PT

localization/languages/ko.json
=> Update Ko string

js/webviewMenu.js, localization/languages/ar.json, localization/languages/bn.json, localization/languages/cs.json, localization/languages/de.json, localization/languages/en-US.json, localization/languages/es.json, localization/languages/fa.json, localization/languages/fr.json, localization/languages/hu.json, localization/languages/it.json, localization/languages/ja.json, localization/languages/ko.json, localization/languages/lt.json, localization/languages/pl.json, localization/languages/pt-BR.json, localization/languages/pt-PT.json, localization/languages/ru.json, localization/languages/tr_TR.json, localization/languages/uk.json, localization/languages/uz.json, localization/languages/vi.json, localization/languages/zh-CN.json, localization/languages/zh-TW.json
=> Add Save Link As to context menu

js/webviewMenu.js, localization/languages/ar.json, localization/languages/bn.json, localization/languages/cs.json, localization/languages/de.json, localization/languages/en-US.json, localization/languages/es.json, localization/languages/fa.json, localization/languages/fr.json, localization/languages/hu.json, localization/languages/it.json, localization/languages/ja.json, localization/languages/ko.json, localization/languages/lt.json, localization/languages/pl.json, localization/languages/pt-BR.json, localization/languages/pt-PT.json, localization/languages/ru.json, localization/languages/tr_TR.json, localization/languages/uk.json, localization/languages/uz.json, localization/languages/vi.json, localization/languages/zh-CN.json, localization/languages/zh-TW.json
=> Add Copy Email Address to context menu

localization/languages/ko.json
Natively and matched to 250 line.
=> Fix Ko string

localization/languages/bg.json
Added a translation to Bulgarian language. 
For some stuff, I followed the proven translations from `Firefox`. For others I searched a lot to insure that my choices of words are correct. I have also checked a couple of times for misspellings (*didn't find any in the last check*).
=> Bulgarian translation

js/webviewMenu.js
fixes #60, fixes #119, fixes #1153
=> Use openTabsInForeground setting for context menu

js/contextMenu.js, localization/languages/ar.json, localization/languages/bg.json, localization/languages/bn.json, localization/languages/cs.json, localization/languages/de.json, localization/languages/en-US.json, localization/languages/es.json, localization/languages/fa.json, localization/languages/fr.json, localization/languages/hu.json, localization/languages/it.json, localization/languages/ja.json, localization/languages/ko.json, localization/languages/lt.json, localization/languages/pl.json, localization/languages/pt-BR.json, localization/languages/pt-PT.json, localization/languages/ru.json, localization/languages/tr_TR.json, localization/languages/uk.json, localization/languages/uz.json, localization/languages/vi.json, localization/languages/zh-CN.json, localization/languages/zh-TW.json
=> Add Paste and Go to address bar context menu

localization/languages/ko.json
=> Update Ko string.

js/navbar/tabBar.js
=> Add drag and drop support to tab bar

localization/languages/tr.json
It's done, hope it will help you.
=> Turkish Translation Update

resources/postinst_script
https://github.com/minbrowser/min/issues/778
=> Solution for sandbox bug in Debian based distro

localization/languages/bn.json
Added the missing/null translation for bn.json
=> Updated bn.json

localization/languages/ko.json
=> Update Ko strings

pages/settings/settings.js
=> Fix disabling built-in password manager

README.md
I think this will look good on our read me...
=> add discord online badge

localization/languages/tr.json
I'm trying to keep this file updated. And still waiting for the Keyboard Shortcut entries to came here.
=> Added Latest User Statistics Translation

main/main.js
=> Fix opening local files

localization/languages/ru.json, localization/languages/uk.json
Removed duplicate translation strings
=> Update uk.json & ru.json

main/main.js, pages/settings/settings.js
This basically persists the restart banner until you actually restart.
=> improve restart

js/menuRenderer.js
=> Make "save page" work for non-html files

main/menu.js
This updates some hardcoded shortcuts for the menu.
Fixes #1486
=> update some shortcuts

localization/languages/ko.json
=> Update Korean tralslations.

localization/languages/de.json
Add the missing German translations.
=> Update German translation

localization/languages/ar.json, localization/languages/bg.json, localization/languages/bn.json, localization/languages/cs.json, localization/languages/de.json, localization/languages/en-US.json, localization/languages/fa.json, localization/languages/fr.json, localization/languages/hu.json, localization/languages/it.json, localization/languages/ja.json, localization/languages/ko.json, localization/languages/lt.json, localization/languages/pl.json, localization/languages/pt-BR.json, localization/languages/pt-PT.json, localization/languages/ru.json, localization/languages/tr.json, localization/languages/uk.json, localization/languages/uz.json, localization/languages/vi.json, localization/languages/zh-CN.json, localization/languages/zh-TW.json, main/main.js, main/viewManager.js
This PR adds a dialog to handle opening links in external applications. Fixes #411, #1224
Screenshots:
=> Add external protocol handling support

js/webviews.js, localization/languages/ar.json, localization/languages/bg.json, localization/languages/bn.json, localization/languages/cs.json, localization/languages/de.json, localization/languages/en-US.json, localization/languages/es.json, localization/languages/fa.json, localization/languages/fr.json, localization/languages/hu.json, localization/languages/it.json, localization/languages/ja.json, localization/languages/ko.json, localization/languages/lt.json, localization/languages/pl.json, localization/languages/pt-BR.json, localization/languages/pt-PT.json, localization/languages/ru.json, localization/languages/tr.json, localization/languages/uk.json, localization/languages/uz.json, localization/languages/vi.json, localization/languages/zh-CN.json, localization/languages/zh-TW.json, pages/settings/index.html, pages/settings/settings.js
=> Add autoplay setting

main/menu.js
Fixes #1558 
CC @Milo123459 Hopefully this makes it clearer what the problem is. It's also easier to see if you look at the settings file [here](https://github.com/minbrowser/min/issues/1558#issuecomment-817263440), specifically this:
```
"addTab":["mod+t","mod+е"],"addPrivateTab":["shift+mod+p","shift+mod+з"]
```
=> Fix getting menu keybinding when multiple bindings are set

main/main.js
Hi, :wave:
I did only **destructuring** object from electron module :heart: 
i commented prev code, then, if you want to remove, remove comment and use :bulb: 
[**mozila docs**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#object_destructuring)
=> Update main.js (Object destructuring)

localization/languages/fa.json
i think, you should **rename** this file to **Persian** (pr.json), because we not have **_Farsi_**,
actually **Farsi**, is Arabic name for Persian language with **Dari** branch (in Iran, Afghanistan, ..) and other branch is Pashto, Urdo, Tajik (or Tajikistan),
because **Parsi** is Persian name for **Persian** language, but **Arabic** not have **P** sound, then, say **Farsi** :wink: 
in Persian, we have some word that have Arabic nouns also, example,
نام => name (sound : Nām)
but, we also Arabic word for this, but not common, 
اسم => name (sound : Esm)
thank :heart:
=> Update fa.json (pr.json)

css/downloadManager.css
=> Fix margin of #download-close-button

localization/languages/it.json
Updated italian translation and fixed missing translations
=> Updated italian translation

js/navbar/tabBar.js, js/tabState/tab.js
URL will be the tab title if no `title` tag exists. Currently tabs just show "New Tab" if that's the case.
=> Use URL if site has no <title>

js/searchbar/searchbarPlugins.js, js/searchbar/searchbarUtils.js
Pretty simple PR but kinda useful. While you are writing a URL you can go to the suggestion and autocomplete the rest using the right arrow.
Example:
https://user-images.githubusercontent.com/63729414/122600972-d1638c80-d02d-11eb-8656-41d53417b883.mov
=> Right arrow to partially autocomplete URL

main/filtering.js
Fixes #1151
@lubiedo Would you be willing to review?
=> Remove tracking parameters from URLs

localization/languages/it.json
=> Fix it.json

main/download.js
Check if the item filename differs from the basename in path and update
the name in the download bar.
=> Fix issue #1720

js/browserUI.js, js/menuRenderer.js, js/tabState/tab.js, main/download.js
=> Correctly detect plaintext files and download instead of saving as HTML

localization/languages/ko.json
=> Update Korean translation

localization/languages/tr.json
PR https://github.com/minbrowser/min/pull/1736 accidentally deleted closed brace.
=> Fix tr.json

main/remoteActions.js
=> Fix bookmark import/export not working on some Linux environments

localization/languages/hr.json
Let's add Croatian translation!
=> Add hr.json

README.md
Includes Arch Linux "Installation on Linux" description.
=> Update README.md to include Arch Linux

localization/languages/vi.json
I've updated with my own Vietnamese skill.
Please check and tells if there is anything that could go wrong.
Could you please explain me the meaning of `bangs`?. This should help me a lot finding the correct translation for it.
Thank you.
=> update Vietnamses Translation

localization/languages/be.json
I added support for Belarusian language, because community of Belarusian-speaking programmers is fast growing.
=> Add localization for Belarusian language

localization/languages/ru.json
Added translation to ru.json in settingsDarkModeSystem row
=> Added translation to ru.json in settingsDarkModeSystem row

localization/languages/de.json
Added some missing translations.
Additionally, German has a familiar and polite form of addressing someone in the second person. I unified the usage of the informal version in some translations as well.
=> Added missing translations for German language

localization/languages/tr.json
There is no specific translated word for bang. I think it is global term. So, it shouldn't be translated.
=> Add missing translations

localization/languages/pt-BR.json
=> Pt-br missing translations

localization/languages/pt-BR.json
Minor spelling corrections and standard translation for the word "tab".
=> Correct spelling and improve translation consistency

js/passwordManager/onePassword.js, js/searchbar/updateNotifications.js, js/util/compareVersions.js, js/util/processWorker.js
=> Update 1password integration to support CLI v2

.gitignore, localization/languages/cs.json
Reviewed and improved Czech localization. Added missing translations.
=> Improve czech localization

localization/languages/pt-BR.json
Text translation for tags in pt-BR.
=> feat: inclusion of missing texts in the pt-BR translation

localization/languages/id.json
Truly a minimal browser and the performance is good too, I don't regret knowing this...
In this pull request, I'd like to add a localization for Indonesian language. I used Firefox's for references so it better be well understood for others too!
=> Add Indonesian localization

localization/languages/de.json
- Add missing german translations for tag management
- Fix translation for key 'tasksSearchTabs'
=> Update de translations

localization/languages/el.json
Added a new el.json file in the localization/languages directory.
=> Added Greek localization

localization/languages/it.json
Added missing translations on line 53-55, 77, 155, 266.
=> Added some missing translations

localization/languages/pt-BR.json
* Including translation for settings Startup Options
=> update: translation PT-BR

localization/languages/nl.json
=> add dutch localization

localization/languages/da.json
=> Added Danish localization

js/places/tagIndex.js, js/searchbar/bookmarkManager.js
This seems to work pretty well on my bookmarks file. It's hard to tell how well it generalizes though - if anyone tries it out on their file, let me know the results!
=> Improve bookmark tag suggestions

localization/languages/hu.json
Updated hu.json, I have included a few missing translations
=> Localization (updated hu.json)

localization/languages/zh-CN.json
Currently, I've completed all of missing translations and modified some of translations, which make them more unified.
=> feat: complete Chinese translation

main/menu.js, scripts/buildMain.js
=> Use keyMap for displaying menu item shortcuts

localization/languages/pt-BR.json
added translations in null fields, translations based on the en-US.js file in the localization folder.
=> Improved Brazilian Portuguese localization

js/defaultKeybindings.js, js/keybindings.js, js/taskOverlay/taskOverlay.js
Fixes #357, #2420, also related to https://github.com/minbrowser/min/discussions/2404
=> Fix cmd+w shortcut in task overlay

localization/languages/ko.json
Improve Korean translation.
Corrected incorrect words and grammar and made it easier to understand.
=> Improve Korean translation.

localization/languages/tr.json
Added Turkish translations for the none existing futures
=> Improve Turkish language localization

package.json, pages/pdfViewer/index.html, pages/pdfViewer/viewer.js
Needed to address https://github.com/mozilla/pdf.js/security/advisories/GHSA-wgrm-67xf-hhpq.
This may have some bugs in it; but hopefully they are minimal and can be addressed in a future release.
=> Upgrade PDFJS
